app/notifications/components/NotificationEmptyState.tsx, app/notifications/components/NotificationHeader.tsx, app/notifications/components/NotificationIcon.tsx, app/notifications/components/NotificationItem.tsx, app/notifications/components/NotificationList.tsx, app/notifications/components/NotificationSkeleton.tsx, app/notifications/components/NotificationTabs.tsx, app/notifications/page.tsx, app/notifications/settings/components/NotificationPolicyInfo.tsx, app/notifications/settings/components/NotificationSettingHeader.tsx, app/notifications/settings/components/NotificationSettingItem.tsx, app/notifications/settings/components/NotificationSettingSkeleton.tsx, app/notifications/settings/page.tsx, components/ui/switch.tsx
=> Feat: 알림 페이지 컴포넌트 분리

app/mypage/components/LogoutDialog.tsx, app/mypage/components/MenuList.tsx, app/mypage/components/MypageHeader.tsx, app/mypage/edit/components/SuccessNotice.tsx, app/mypage/edit/components/card/EmailChangeDialog.tsx, app/mypage/edit/components/card/ProfileCard.tsx, app/mypage/edit/components/card/ProfileCardHeader.tsx, app/mypage/edit/components/card/ProfileForm.tsx, app/mypage/edit/components/header/ProfileHeader.tsx, app/mypage/edit/page.tsx, app/mypage/page.tsx, components/ui/dialog.tsx
Close #
- 유저의 마이페이지의 컴포넌트를 분리했습니다.
- 마이페이지에서 정보 수정하는 페이지의 컴포넌트를 분리했습니다
=> Feat: 유저 마이페이지 컴포넌트 분리

app/signup/wallet/password/components/SimplePasswordStep.tsx
Close #17 
- virtual keypad 컴포넌트를 수정함에 따라 회원가입 시 간편 비밀번호 입력 화면에 대해 수정했습니다
간편 비밀번호 입력 시 h2 컴포넌트 추가
상태에 따라서 간편 비밀번호 입력, 간편 비밀번호 재입력으로 h2 내용 변경되도록 적용
=> refactor: virtual keypad 컴포넌트 분리 적용

app/wallet/page.tsx
Close #
- 지갑 조회 부분 api 경로 수정
- /api/wallet/balance로 경로 수정
=> refactor: api 경로 수정

app/wallet/components/ProcessingStep.tsx, app/wallet/convert/[type]/page.tsx
Close #14
- 토큰에서 예금으로 전환이 안되는 이슈를 해결했습니다
=> fix: 토큰에서 예금 전환 이슈 해결

app/my-vouchers/components/MyStoreModal.tsx, app/my-vouchers/details/[voucherOwnershipId]/page.tsx, app/my-vouchers/page.tsx, app/vouchers/purchase/verify/page.tsx, components/common/LoadingOverlay.tsx, next.config.ts
Close #46 
- LoadingOverlay (로딩 페이지) 공통 컴포넌트화
- 내 바우처 로딩 시 스켈레톤 UI 적용
- StoreModal의 ux 개선 
- 모달 창이 아닌 배경을 탭해도 나가짐
- 모달 창을 띄운 후 스크롤 시 페이지 전체가 스크롤 되는 현상 해결
=> Refactor: 내 바우처 코드 리팩토링

app/wallet/convert/[type]/page.tsx
Close #14 
- 예금 토큰 전환 오류 수정
죄송함니다...
=> fix: 전환하기 페이지 오류 해결

app/dashboard/api/wallet-info.ts, app/payment/api/payment.ts, app/payment/components/AmountBox.tsx, app/payment/components/ManualBox.tsx, app/payment/components/MerchantInfoCard.tsx, app/payment/components/PaymentCarousel.tsx, app/payment/components/ResultBox.tsx, app/payment/components/VerifySimplePassword.tsx, app/payment/page.tsx, app/payment/qr-test/page.tsx, app/wallet/totaltransaction/page.tsx, data/payment/storeqr.ts
Close #16
- 결제 시 QR 인식 api 연동
- 거래번호 생성
=> ✨ feat: QR 인식 api 연동

app/dashboard/api/fetch-notice-preview.ts, app/dashboard/api/fetch-recent-transactions.ts, app/dashboard/api/wallet-info.ts, app/dashboard/page.tsx, app/notice/[id]/page.tsx, app/notice/page.tsx, app/offline-stores/api/store-service.ts, app/payment/api/payment.ts, app/wallet/api/fetch-transactions-detail.ts, app/wallet/api/fetch-transactions.ts, app/wallet/api/wallet.ts, app/wallet/page.tsx, app/wallet/totaltransaction/[id]/page.tsx, app/wallet/totaltransaction/page.tsx, lib/api/voucher.ts, lib/filterLatestNotices.ts
Close #57 
- uri 엔드포인트 변경에 따른 fetch 코드 업데이트
- page.tsx에 있던 fetch 코드 분리
=> refactor: uri 엔드포인트 변경 반영

app/merchant/dashboard/components/VoucherSearch.tsx, app/merchant/wallet/components/ConvertButton.tsx, app/merchant/wallet/convert/api/token-to-deposit.ts, app/merchant/wallet/convert/api/verify-merchant-simple-password.ts, app/merchant/wallet/convert/components/AmountStep.tsx, app/merchant/wallet/convert/components/BalanceCard.tsx, app/merchant/wallet/convert/components/CompleteStep.tsx, app/merchant/wallet/convert/components/ConfirmStep.tsx, app/merchant/wallet/convert/components/ConvertPreview.tsx, app/merchant/wallet/convert/components/ProcessingStep.tsx, app/merchant/wallet/convert/components/VerifySimplePassword.tsx, app/merchant/wallet/convert/page.tsx
Close #61
- 가맹점주 지갑 페이지 구현
- 가맹점주 지갑 페이지에서 토큰을 예금으로 변환하는 api에 대해서 연동했습니다
=> Feat: 가맹점주 토큰 -> 예금 전환 페이지 구현

app/merchant/notice/[id]/page.tsx, app/merchant/notice/api/notice-api.ts, app/merchant/notice/components/NoticeItem.tsx, app/merchant/notice/components/NoticeList.tsx, app/merchant/notice/components/SkeletonDetail.tsx, app/merchant/notice/components/SkeletonList.tsx, app/merchant/notice/page.tsx
Close #62 
- 가맹점주 공지사항 페이지 구현
가맹점주 공지사항 조회 페이지는 유저와 공지사항 내용조차 같아서 크게 변경사항 없습니다.
연동해둔 uri만 수정했습니다~
=> feat: 가맹점주 공지사항 페이지 구현 및 api 연동

app/wallet/components/common/TransactionList.tsx
Close #16
- 파일이 하나 빠져서 다시 올립니당...
=> refactor: 결제내역 조회 관련 수정

app/mypage/change-password/api/password-update.ts, app/mypage/change-password/components/ChangePasswordCardHeader.tsx, app/mypage/change-password/components/ChangePasswordForm.tsx, app/mypage/change-password/components/ChangePasswordHeader.tsx, app/mypage/change-password/components/ChangePasswordSuccess.tsx, app/mypage/change-password/components/PasswordInput.tsx, app/mypage/change-password/page.tsx, app/mypage/page.tsx
Close #25 
- 유저의 비밀번호를 변경할 수 있는 페이지를 구현했습니다
- api 연동까지 완료했습니다
가맹점주 UI와 동일하게 구현했습니다!
=> feat: 유저 비밀번호 변경 페이지 구현

app/vouchers/components/PurchaseTokenBalance.tsx, app/vouchers/details/[id]/loading/Skeleton.tsx, app/vouchers/details/[id]/page.tsx, app/vouchers/purchase/page.tsx
Close #50 
- 바우처 상세 보기 404 에러 해결
- 바우처 구매 시 지갑에서 이름이 나오지 않는 에러 해결
=> Fix: 바우처 상세 보기 404 에러 해결

app/merchant/dashboard/page.tsx, app/merchant/mypage/change-simple-password/components/ChangePinHeader.tsx
=> refactor: UI 수정

app/merchant/wallet/convert/components/VerifySimplePassword.tsx, app/merchant/wallet/convert/page.tsx
Close #61
- 유저와 마찬가지로 간편 비밀번호 인증 api 요청 제거 및 간편 비밀번호 확인 버튼 비활성화 기능 추가
=> refactor: 간편비밀번호 검증 요청 api 제거

app/dashboard/page.tsx, app/merchant/wallet/convert/components/AmountStep.tsx, app/wallet/components/AmountStep.tsx, app/wallet/components/common/TransactionCardContent.tsx, app/wallet/components/common/TransactionList.tsx, app/wallet/page.tsx, app/wallet/totaltransaction/[id]/page.tsx, app/wallet/totaltransaction/page.tsx, components/common/AmountInput.tsx
Close #
- 유저 페이지의 ui를 개선했습니다
거래내역 부분은 멘토님 피드백이 있었어서 추후 추가적으로 수정할 예정입니다~
=> refactor: user page ui 수정

app/merchant/mypage/qr-code/components/MerchantInfoCard.tsx, app/merchant/mypage/qr-code/components/PaymentGuideSection.tsx, app/merchant/mypage/qr-code/components/QRCodeSection.tsx, app/merchant/mypage/qr-code/components/QrHeader.tsx, app/merchant/mypage/qr-code/data/storeqr.ts, app/merchant/mypage/qr-code/page.tsx, package-lock.json, package.json
Close #75 
- 가맹점주가 QR코드를 조회할 수 있는 화면을 구현했습니다
UI 피드백 부탁드립니다~
=> feat: QRCode 화면 구현

app/notifications/api/delete-notifications.ts, app/notifications/api/fetch-notifications-category.ts, app/notifications/api/fetch-notifications.ts, app/notifications/components/NotificationIcon.tsx, app/notifications/components/NotificationItem.tsx, app/notifications/components/NotificationList.tsx, app/notifications/components/NotificationTabs.tsx, app/notifications/page.tsx, app/notifications/settings/api/fetch-notification-setting.ts, app/notifications/settings/api/update-notification-setting.ts, app/notifications/settings/components/NotificationPolicyInfo.tsx, app/notifications/settings/page.tsx
Close #4 
- 알림 페이지에 api를 연동했습니다
- 알림 목록 조회
- 알림 카테고리별 조회
- 알림 삭제
- 알림 설정 조회
- 알림 설정 업데이트
- 알림 로딩시 스켈레톤 적용
- 알림 목록 조회
- 알림 카테고리별 조회
- 알림 삭제 모달
- 알림 설정
=> feat: 알림 페이지 구현

app/payment/components/PaymentCarousel.tsx, app/payment/page.tsx
Close #74 
- PaymentCarousel ui 수정
<수정 전>
<수정 후>
=> refactor: PaymentCarousel ui 수정

app/dashboard/page.tsx, app/notifications/page.tsx, components/common/NotificationToast.tsx, package-lock.json, package.json
Close #4 
- SSE 알림 발생 시 화면에 toast-ui가 반영되도록 api를 연동하고 toast 컴포넌트를 구현했습니다
=> feat: 알림 기능 연동

.github/workflows/deploy.yml, Dockerfile
Close #99 
- Deploy.yml에 CodeDeploy 추가
=> :sparkles: Feat: CICD 파일 추가

app/wallet/totaltransaction/[id]/page.tsx
Close #14
- txHash가 null 값인 경우에 대해 예외 처리를 했습니다
=> refactor: txHash 예외처리

app/merchant/signup/business/components/AddressSearchModal.tsx, app/merchant/signup/business/components/InfoStep.tsx
Close #109
- merchant/signup/buisness 수정
1. 사업자 등록번호 000-00-00000 형식으로 수정
- 회원가입과 로그인의 placehorder와 번호 형식이 달라 자격증명이 실패하던 부분 고침
2. 주소 입력 카테고리 드롭박스 3개 수정 (서연이꺼 반영)
=> Refactor: 가맹점주 회원가입 business 부분 수정

app/dashboard/page.tsx
Close #3
- SSE 연동 후 발생하던 Hikaripool 에러에 대해 해결했습니다
- 대시보드에서 다른 페이지로 이동했을 때, 해당 연결을 끊고 다시 대시보드로 돌아왔을 때 SSE를 재연결하여 알림을 보여주도록 수정
=> fix: Hikaripool error 해결

app/merchant/mypage/qr-code/data/storeqr.ts
=> refactor: merchant qrcode 수정

app/offline-stores/[id]/page.tsx, app/offline-stores/api/store-api.ts, app/offline-stores/components/LoadingSpinner.tsx, app/offline-stores/components/StoreQrBunny.tsx, app/offline-stores/page.tsx, app/offline-stores/utils/map-utils.ts
Close #114 
- 카카오맵에 로딩을 추가하고, api를 최적화 하였습니다
- 카카오맵에 상점 상세 페이지를 구현하였습니다.
=> Feat/#114 kakao map 상세 페이지 구현 및 클러스터링 적용 완료

app/dashboard/loading/NoticeSkeleton.tsx, app/dashboard/loading/TransactionListSkeleton.tsx, app/dashboard/loading/WalletCardSkeleton.tsx, app/dashboard/page.tsx, app/landing-page/components/CBDCTab.tsx, app/landing-page/components/PullHandle.tsx, app/mypage/change-pin/components/StepIntro.tsx, app/mypage/change-pin/components/StepVerifyCurrent.tsx, app/mypage/change-pin/page.tsx, app/mypage/components/MypageSkeleton.tsx, app/mypage/page.tsx, app/payment/components/VerifySimplePassword.tsx, app/payment/page.tsx, app/wallet/components/AmountStep.tsx, app/wallet/components/convertSkeleton.tsx, app/wallet/convert/[type]/page.tsx, app/wallet/page.tsx, components/common/Header.tsx, components/common/NotificationToast.tsx, lib/fetchWithAuth.ts
Close #112 
- Skeleton 적용 및 UI  수정
=> Refactor: Skeleton 적용 및 UI  수정

app/merchant/signup/business/components/AddressSearchModal.tsx, app/merchant/signup/business/components/InfoStep.tsx, app/merchant/signup/business/page.tsx, app/offline-stores/page.tsx, app/offline-stores/utils/map-overlay.ts, app/offline-stores/utils/map-utils.ts, app/payment/page.tsx, components/qr-code.tsx, components/ui/chart.tsx
Close #114
- 카카오맵 관련 타입 에러를 수정하였습니다
- 검색기능 사용시 클러스터가 변경되지 않던 부분을 수정하였습니다.
- 마커를 클릭하면 오버레이 표출과 관계없이 상세페이지로 이동되던 이슈를 해결하였습니다.
=> :bug: fix: KaKao Type Error 해결

app/vouchers/components/VoucherCard.tsx, next.config.ts
- next.config.ts 파일 수정
- 운영 배포 트리거 (`main` push → Actions → CodeDeploy)
=> [DEPLOY] v1.0.3

app/vouchers/components/VoucherCard.tsx, app/vouchers/purchase/page.tsx, lib/api/getImageSrc.ts, next.config.ts
- next.config.ts 파일 수정 및 바우처 이미지 조회 에러 수정
- 운영 배포 트리거 (`main` push → Actions → CodeDeploy)
=> [DEPLOY] v1.0.4

app/merchant/dashboard/page.tsx, app/merchant/notifications/api/delete-merchant-notifications.ts, app/merchant/notifications/api/fetch-merchant-notifications-category.ts, app/merchant/notifications/api/fetch-merchant-notifications.ts, app/merchant/notifications/components/NotificationEmptyState.tsx, app/merchant/notifications/components/NotificationHeader.tsx, app/merchant/notifications/components/NotificationIcon.tsx, app/merchant/notifications/components/NotificationItem.tsx, app/merchant/notifications/components/NotificationList.tsx, app/merchant/notifications/components/NotificationSkeleton.tsx, app/merchant/notifications/components/NotificationTabs.tsx, app/merchant/notifications/page.tsx, app/merchant/notifications/settings/api/fetch-merchant-notification-setting.ts, app/merchant/notifications/settings/api/update-merchant-notification-setting.ts, app/merchant/notifications/settings/components/NotificationPolicyInfo.tsx, app/merchant/notifications/settings/components/NotificationSettingHeader.tsx, app/merchant/notifications/settings/components/NotificationSettingItem.tsx, app/merchant/notifications/settings/components/NotificationSettingSkeleton.tsx, app/merchant/notifications/settings/page.tsx, app/merchant/wallet/convert/components/CompleteStep.tsx, app/merchant/wallet/convert/page.tsx
Close #116 
- 가맹점주 알림 기능을 구현했습니다
- 가맹점주 알림 목록 조회 페이지 구현 및 api 연동
- 가맹점주 알림 목록 카테고리별 조회 페이지 구현 및 api 연동
- 가맹점주 알림 설정 페이지 구현 및 api 연동
- 가맹점주 SSE, SMTP 연동
=> feat: 가맹점주 알림 페이지 구현 및 api 연동

app/my-vouchers/components/MyVoucherCard.tsx, app/my-vouchers/components/MyVoucherHeader.tsx, app/my-vouchers/details/[voucherOwnershipId]/page.tsx, app/vouchers/components/HeaderImage.tsx, app/vouchers/components/VoucherCard.tsx, app/vouchers/components/VoucherPurchaseCard.tsx, app/vouchers/purchase/page.tsx, lib/api/getImageSrc.ts, next.config.ts
=> Refactor: 이미지 경로 설정을 환경에 따라 동적으로 처리

app/dashboard/page.tsx, cypress/e2e/merchant/signup.cy.ts, cypress/e2e/user/signup.cy.ts
🚀 Release v1.0.5
✅ 주요 변경 사항
ui 수정 및 알림 구현
build error 해결
🎯 머지 목적
=> [DEPLOY] v1.0.5

app/merchant/wallet/components/WalletClient.tsx, app/merchant/wallet/page.tsx
Close #61 
- build error 해결을 위해 컴포넌트를 추가로 분리했습니다
=> fix: build 에러 해결
